import { useState, useEffect, useCallback } from 'react'
import { improveSection } from '../api/resumeApi'
import './ImproveModal.css'

export default function ImproveModal({ isOpen, onClose, section, result, jobTitle, onApply }) {
  const [step, setStep] = useState('input') // 'input' | 'loading' | 'review'
  const [userInput, setUserInput] = useState('')
  const [projectName, setProjectName] = useState('') // New for projects
  const [generatedOutput, setGeneratedOutput] = useState('')
  const [feedback, setFeedback] = useState('')
  const [feedbackHistory, setFeedbackHistory] = useState([])
  const [error, setError] = useState(null)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Skills-specific state
  const [skillTags, setSkillTags] = useState([])
  const [newSkillInput, setNewSkillInput] = useState('')

  const handleGenerate = useCallback(async (isRegenerate = false, extraFeedback = '') => {
    setStep('loading')
    setError(null)

    let currentHistory = [...feedbackHistory]
    const usedFeedback = extraFeedback || feedback

    if (isRegenerate && usedFeedback.trim()) {
      currentHistory.push({ role: 'ai', content: generatedOutput })
      currentHistory.push({ role: 'user', content: usedFeedback })
      setFeedbackHistory(currentHistory)
    } else if (!isRegenerate) {
      setFeedbackHistory([])
      currentHistory = []
    }

    try {
      const res = await improveSection(section, result, jobTitle, userInput, currentHistory)
      const output = res.generated_output
      setGeneratedOutput(output)

      // Parse skills into tags and deduplicate (case-insensitive)
      if (section === 'skills') {
        const parsed = output.split(',').map(s => s.trim()).filter(s => s)
        const seen = new Set()
        const unique = parsed.filter(s => {
          const key = s.toLowerCase()
          if (seen.has(key)) return false
          seen.add(key)
          return true
        })
        setSkillTags(unique)
      }

      setStep('review')
      setFeedback('')
    } catch (err) {
      setError(err.message || 'Failed to generate improvement')
      setStep(isRegenerate ? 'review' : 'input')
    }
  }, [section, result, jobTitle, userInput, feedbackHistory, feedback, generatedOutput])

  useEffect(() => {
    if (isOpen && (section === 'title' || section === 'skills') && !hasAutoGenerated) {
      setHasAutoGenerated(true)
      handleGenerate(false)
    }
  }, [isOpen, section, hasAutoGenerated, handleGenerate])

  if (!isOpen) return null

  const handleApply = (shouldClose = true) => {
    if (section === 'skills') {
      onApply(section, skillTags.join(', '))
    } else if (section === 'projects') {
      // Pass both name and description
      const projectData = JSON.stringify({
        name: projectName || '✨ AI Tailored Project',
        description: generatedOutput
      })
      onApply(section, projectData)
    } else {
      onApply(section, generatedOutput)
    }

    if (shouldClose) {
      handleClose()
    } else {
      // Just reset for next project
      setStep('input')
      setUserInput('')
      setProjectName('')
      setGeneratedOutput('')
      setFeedback('')
      setFeedbackHistory([])
    }
  }

  const handleClose = () => {
    setStep('input')
    setUserInput('')
    setProjectName('')
    setGeneratedOutput('')
    setFeedback('')
    setFeedbackHistory([])
    setError(null)
    setHasAutoGenerated(false)
    setSkillTags([])
    setNewSkillInput('')
    onClose()
  }

  const removeSkillTag = (index) => {
    setSkillTags(prev => prev.filter((_, i) => i !== index))
  }

  const addManualSkill = () => {
    const trimmed = newSkillInput.trim()
    if (trimmed && !skillTags.includes(trimmed)) {
      setSkillTags(prev => [...prev, trimmed])
    }
    setNewSkillInput('')
  }

  const handleRefreshSkills = () => {
    const currentTagsStr = skillTags.join(', ')
    handleGenerate(true, `Here are the skills I currently have selected: ${currentTagsStr}. Please suggest a fresh new set of relevant skills.`)
  }

  const getPlaceholder = () => {
    if (section === 'objective') return "E.g., I want to highlight my 3 years of React experience and my transition to full-stack."
    if (section === 'projects') return "E.g., Developed a microservices-based order management system that handled 10k orders/day."
    return "Enter details..."
  }

  return (
    <div className="modal-overlay">
      <div className="modal-card">
        <button className="modal-close" onClick={handleClose}>✕</button>
        
        <h2 className="modal-title">✨ Improve {section.charAt(0).toUpperCase() + section.slice(1)}</h2>
        
        {error && <div className="modal-error">⚠️ {error}</div>}

        {step === 'input' && (
          <div className="modal-step fade-in">
            <p className="modal-desc">
              Tell the AI what you want to highlight for the <strong>{jobTitle}</strong> role.
            </p>
            
            {section === 'projects' && (
              <div className="project-name-input-group">
                <label className="input-label">Project Name</label>
                <input 
                  className="modal-input" 
                  placeholder="e.g. Portfolio Website, E-commerce App"
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                />
                <label className="input-label">What did you build/do?</label>
              </div>
            )}

            <textarea
              className="modal-textarea"
              placeholder={getPlaceholder()}
              value={userInput}
              onChange={(e) => setUserInput(e.target.value)}
              rows={4}
            />
            <div className="modal-actions">
              <button className="btn-secondary" onClick={handleClose}>Cancel</button>
              <button 
                className="btn-primary" 
                onClick={() => handleGenerate(false)}
                disabled={!userInput.trim() || (section === 'projects' && !projectName.trim())}
              >
                Generate Draft →
              </button>
            </div>
          </div>
        )}

        {step === 'loading' && (
          <div className="modal-step fade-in loading-step">
            <div className="spinner-modal" />
            <p>LangGraph AI is analyzing your {section}...</p>
          </div>
        )}

        {step === 'review' && section === 'skills' && (
          <div className="modal-step fade-in review-step">
            <div className="ai-draft-container">
              <div className="draft-badge">AI Suggested Skills</div>
              <p className="skills-hint">Click a tag to remove it. Add your own below.</p>
              <div className="skill-tags-container">
                {skillTags.map((skill, i) => (
                  <span key={i} className="skill-tag-editable" onClick={() => removeSkillTag(i)}>
                    {skill} <span className="tag-remove">✕</span>
                  </span>
                ))}
              </div>
            </div>

            {/* Manual add skill */}
            <div className="add-skill-row">
              <input
                type="text"
                className="feedback-input"
                placeholder="+ Add a skill manually (e.g. Docker)"
                value={newSkillInput}
                onChange={(e) => setNewSkillInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addManualSkill()}
              />
              <button className="btn-secondary btn-sm" onClick={addManualSkill} disabled={!newSkillInput.trim()}>
                Add
              </button>
            </div>

            {/* Feedback + Refresh */}
            <div className="feedback-section">
              <p className="feedback-label">Not satisfied? Tell AI what to change or refresh for new suggestions:</p>
              <div className="feedback-input-row">
                <input
                  type="text"
                  className="feedback-input"
                  placeholder="E.g., Add more cloud skills, remove testing tools..."
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                />
                <button
                  className="btn-secondary btn-sm"
                  onClick={() => handleGenerate(true)}
                  disabled={!feedback.trim()}
                >
                  Regenerate 🔄
                </button>
              </div>
              <button className="btn-refresh" onClick={handleRefreshSkills}>
                🔃 Refresh (Fresh Suggestions)
              </button>
            </div>

            <div className="modal-actions apply-actions">
              <button className="btn-secondary" onClick={handleClose}>Cancel</button>
              <button className="btn-primary" onClick={() => handleApply(true)} disabled={skillTags.length === 0}>
                ✅ Apply {skillTags.length} Skills
              </button>
            </div>
          </div>
        )}

        {step === 'review' && section !== 'skills' && (
          <div className="modal-step fade-in review-step">
            <div className="ai-draft-container">
              <div className="draft-badge">AI Draft {section === 'projects' && `for ${projectName}`}</div>
              <pre className="ai-draft">{generatedOutput}</pre>
            </div>

            <div className="feedback-section">
              <p className="feedback-label">Not quite right? Give feedback to iterate:</p>
              <div className="feedback-input-row">
                <input
                  type="text"
                  className="feedback-input"
                  placeholder="E.g., Make it shorter, focus more on database optimization..."
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                />
                <button 
                  className="btn-secondary btn-sm" 
                  onClick={() => handleGenerate(true)}
                  disabled={!feedback.trim()}
                >
                  Regenerate 🔄
                </button>
              </div>
            </div>

            <div className="modal-actions apply-actions">
              {!(section === 'title' || section === 'skills') && (
                <button className="btn-secondary" onClick={() => setStep('input')}>← Back</button>
              )}
              <button className="btn-secondary" onClick={handleClose}>Cancel</button>
              
              {section === 'projects' ? (
                <>
                  <button className="btn-secondary btn-outline" onClick={() => handleApply(false)}>
                    ➕ Add & Next
                  </button>
                  <button className="btn-primary" onClick={() => handleApply(true)}>
                    ✅ Add & Finish
                  </button>
                </>
              ) : (
                <button className="btn-primary" onClick={() => handleApply(true)}>
                  ✅ Apply to Resume
                </button>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
